### ISSUE TITLE
Edit rmds to identify your FMC

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [Openscapes/2021-noaa-nmfs#16]
Update your markdown docs to identify which FMC you're from

- [x] Alicia
- [x] Skyler
- [ ] Megsie
- [x] Laurie

**Comment by jules32** [comment]
Nice assignments!

**Comment by skylersagarese-NOAA** [comment]
I added my affliation at https://github.com/Openscapes/2021-noaa-nmfs/edit/main/github-clinic/skyler-sagarese.md

**Comment by LaurieWeit** [comment]
This is a comment on the issue.  Need to do three things:

- [ ] first thing
- [ ] second thing
- [ ] third thing
