### ISSUE TITLE
Have first AFSC team Seaside chat

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [Openscapes/2021-noaa-nmfs#22]
This is mostly to test out issues and a project board. And we can check it off after our first meeting!

Chat about:

- [x] team needs
- [x] team goals

**Comment by Ned-Laman-NOAA** [comment]
Nice!
BTW - I'll probably be a few minutes late to the meeting Monday morning as I'll be returning from an earlier appointment.

**Comment by MargaretSiple-NOAA** [comment]
First Seaside chat done on 9/27. Now we have goals as detailed in #27 !
