### ISSUE TITLE
02_SeasideChat Eco-Stock Assessment

### ISSUE THREAD

**Issue by Curt-Whitmire-NOAA** [Openscapes/2021-noaa-nmfs#33]
**10/08/21, Eco-Stock Assessment**
We shared some ideas for increased collaboration across NWFSC, along with some useful tips and packages to improve our code, reports and websites.

Present
- [ ] @chantelwetzel-noaa 
- [ ] @kellijohnson-NOAA 
- [ ] @cj-harvey 
- [ ] @pmcelhany 
- [ ] @Curt-Whitmire-NOAA 

Absent
- [ ] @correigh 
- [ ] @ShallinBusch 
- [ ] Nick Tolimieri

 Useful resources:
Bookdown
Shiny

**Comment by Curt-Whitmire-NOAA** [comment]
@nanciecummings-NOAA , no Google doc. I'm still editing and will summarize our Seaside chat directly in this issue.

**Comment by nanciecummings-NOAA** [comment]
@Curt-Whitmire-NOAA : many thanks, will stay tuned.
