### ISSUE TITLE
Title for these important methods

### ISSUE THREAD

**Issue by jules32** [Openscapes/2021-noaa-nmfs#6]
Some text about this particular thing.

**Comment by jules32** [comment]
Hey @eeholmes , could you comment on these things: 

- number 1
- thing 2

look at [this link](https://googlecom)

**Comment by jules32** [comment]
Could you look at [these lines of code](https://github.com/amfriesz/lpdaac_hls_tutorial/blob/main/environment.yml#L6-L15)

**Comment by ShallinBusch** [comment]
Noting there that the link was supposed to be [this](https://www.google.com/), I think.

**Comment by vmatter-NOAA** [comment]
Thanks @ShallinBusch

**Comment by CaitlinAkselrud-NOAA** [comment]
trying to link to lines: 
check out these cool data sets @jules32 https://github.com/CaitlinAkselrud-NOAA/myrepo/blob/main/interesting_datasets.R

**Comment by jules32** [comment]
like this! https://github.com/CaitlinAkselrud-NOAA/myrepo/blob/main/interesting_datasets.R#L7-L13
